title: Hello, Data Scientists! Welcome to Data Science in Brief!
description: Data Science in Brief is the non-profit community sharing main purpose on learning, exchanging AI and Data Science knowledge through short articles and hand-on events.
permalink: ':title/'
baseurl: "/static_web"
url: "https://datascienceinbrief.github.io"

# Author Settings
author: Data Science in Brief
author-img: DataScienceInBrief.png
about-author: From Sparse Data To Expert Knowledge
social-facebook: https://www.facebook.com/DSinbrief
social-github: https://github.com/DataScienceinBrief
social-email: DSinbrief@gmail.com

# Disqus
discus-identifier: dsinbrief

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
